### ISSUE TITLE
error in examples (pt_create_pTable())

### ISSUE THREAD

**Issue by bernhard-da** [tenderle/ptable#4] opened 2018-07-06 17:05 UTC
hi,

using the latest version, running:

```
library(devtools)
run_examples()
```

results in

```
....
Running examples in pt_plot.Rd --------------------------------------------------------------------------------------------------------------
> 
> # Simple Example
> params <- pt_create_pParams(D=5, V=2, js=2, label="Example")
> ptable_destatis <- pt_create_pTable(params=params, type="destatis")

Row 2 : original frequency i = 1 
------------------------------- 
error in is.nloptr(ret) : length(lb) != length(x0)
```

**Comment by tenderle** [comment] 2018-07-06 17:28
@bernhard-da Thx, this should be fixed by Version 0.1.4 (5e3bcb372ae298445a9847e337ea338946248c9c)

**Comment by bernhard-da** [comment] 2018-07-06 17:38
i still geht the following:

```
devtools::run_examples()
```

error:

```
...
....
Running examples in pt_plot.Rd -------------------------------------------------------------------------------------------------------------
> 
> # Simple Example
> params <- pt_create_pParams(D=5, V=2, js=2, label="Example")
> ptable_destatis <- pt_create_pTable(params=params, type="destatis")

Row 2 : original frequency i = 1 
------------------------------- 
error in pt_create_pTable(params = params, type = "destatis") : 
The variance parameter you set is too small!
Loading ptable
```

**Comment by tenderle** [comment] 2018-07-06 17:53
@bernhard-da Thx, after using `devtools::run_examples()` I have found no more error examples.

**Comment by tenderle** [comment] 2018-07-06 17:58
I close the issue. If there may arise further errors, you could reopen the issue.

**Closed as completed by tenderle** 2018-07-06 17:58 UTC
Labels: bug

**Comment by pnicky** [comment] 2019-05-13 14:46
Hello, I have this error with my code:

HC_92_HU<- read.csv2("H:/munkafile-ok/hc_92_1010.csv", header=TRUE, sep=";", dec=",", fill=TRUE)
colnames(HC_92_HU)<-c("geo_m", "sex", "age_m", "yae_h", "usual_resident", "spv_cov_imputation_flag")
head(HC_92_HU)

set.seed(123)
options(scipen=999)
#recordkey
HC_92_HU$recordkey<-runif(dim(HC_92_HU)[1])
head(HC_92_HU)

params <- pt_create_pParams(D=3, V=0.9, js=2)
ptable_destatis <- pt_create_pTable(params=params, type="destatis")

Error in pt_create_pTable(params = params, type = "destatis") : 
The variance parameter you set is too small!

What is the solution, how can we fix js to 2?
Thanks!

**Comment by tenderle** [comment] 2019-05-15 08:19
Dear @pnicky, in your case just set `V=2`. However, I will improve the error reporting anyway.

**Comment by pnicky** [comment] 2019-05-15 08:28
Dear @tenderle thank you! But can I set v to 2? Setting V to 1 wasn't good because of p_var.

**Comment by tenderle** [comment] 2019-05-15 08:38
Sorry, you may be right. I will check this issue.

**Comment by tenderle** [comment] 2019-05-15 09:34
Ok, I knew that it worked with `D=3` and `js=2` but it is a little bit more comprehensive (you need to adjust other parameters and choose a variance little bit larger than 2, for example 2.001):

`params=pt_create_pParams(D=3, V=2.001,optim=c(1,1,1,4,1,1), mono=c(T,T,T,F,T,T), js=2)`

The problem is original frequency `i=4`. You have to remove the monotony condition (set mono to FALSE) and use another set of optimization conditions (set optim to 4).

**Comment by tenderle** [comment] 2019-05-15 10:15
@pnicky does this help? If you have further issues or questions, either open a new issue or use the following (more general) page https://github.com/sdcTools/UserSupport/issues

May I ask from which national statistical institute you are from?

Best, 
Tobias

**Comment by pnicky** [comment] 2019-05-15 10:23
@tenderle thanks so much for your ideas. Ok, I'll do this.
My concern is, can I have a V<1 with js=2?
I cannot try them right now, I get back to you tomorrow. Here, I have R3.4 under linux. I guess, I need 3.5.
I work for HCSO (where László Antal also worked).
Best, Niki
